[project]
name = "pidthing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "onnxruntime>=1.22.0",
    "onnxruntime-gpu>=1.22.0",
    "pydantic>=2.11.7",
    "ultralytics>=8.3.160",
]
